name: Release
on: 
  workflow_dispatch:
  push:
    tags: '**'

permissions:
  contents: write
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
    
jobs:
  release:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/realestatepilot/argocd-customtooling

      - name: get Version from current branch tag
        id: getVersion
        run: |
          echo "custom_version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GHCR_IO_TOKEN }}

      - name: Push to container registry
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: argocd_version=${{ env.custom_version }}
          # tags: ${{github.repository}}:${{ env.GIT_TAG_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: ${{ env.custom_version }}

          
