name: Release
on: 
  workflow_dispatch:
  push:
    tags: '**'

    
jobs:
  release:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: realestatepilot/argocd-cutomtooling


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: argocd_version=${{ env.GIT_TAG_NAME }}
          # tags: ${{github.repository}}:${{ env.GIT_TAG_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          push: false

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: ${{ env.GIT_TAG_NAME }}

          
